from .assignement import Assignment
from .declaration import VariableDeclaration
from .variableDeclarationAdnAssignement import VariableDeclarationAndAssignment
from .functionCall import FunctionCall
from .functionDef import FunctionDef
from .constant import Constant
from .name import Name
from .returns import Return
from .ifTest import IfTest
from .compare import Compare
from .operator import Operator
from .binaryOperator import BinaryOperator
from .argument import Argument
from .goto import Goto
from .whileLoop import WhileLoop